### ISSUE TITLE
missing dataset

### ISSUE THREAD

**Issue by CatEek** [CAREamics/careamics-portfolio#27]
`denoising datasets: ['N2V_BSD68', 'N2V_SEM', 'N2V_RGB', 'Flywing', 'Convallaria']
`
`files = portfolio.denoising.Flywing.download(root_path)
`

`AttributeError: 'Denoising' object has no attribute 'Flywing'
`

**Comment by jdeschamps** [comment]
Fixed in https://github.com/CAREamics/careamics-portfolio/commit/4f16aef293510ebf8c6970152b6efb30131cc863
